<fieldset class="fieldset create account" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>">
	<legend class="legend">
		<span><?php /* @escapeNotVerified */ echo __('Bitte tragen Sie die ID Ihres Werbers ein (soweit vorhanden)') ?></span>
	</legend>
	<div class="field referrer">
		<label for="referrer" class="label">
			<span><?php /* @escapeNotVerified */ echo __('Kunden ID') ?></span>
		</label>
		<div class="control">
			<input type="text" checked name="referrer" id="referrer" title="<?php /* @escapeNotVerified */ echo __('Referrer') ?>" class="input-text" data-validate="{required:false}" />
		</div>
	</div>
</fieldset>